event_index:
    path:     /
    defaults: { _controller: CptEventBundle:Event:index }

event_get_calendar_arrow_type:
    path:     /calendar/{year}/{month}/arrowtype
    defaults: { _controller: CptEventBundle:Calendar:getEventSelectorArrowType }
    requirements:
        year:  \d+
        month: \d+
    options:
        expose: true
        
event_manage:
    path:     /edit/{id}
    defaults: { _controller: CptEventBundle:Event:new, id: -1, copy: 0  }
    requirements:
        id:  \d+
        copy: 1|0
    options:
        expose: true 

event_cancel:
    path:     /cancel/{id}
    defaults: { _controller: CptEventBundle:Event:cancelEvent  }
    requirements:
        id:  \d+
        _method: DELETE
    options:
        expose: true 
        
event_view:
    path:     /view/{id}
    defaults: { _controller: CptEventBundle:Event:getEvent  }
    requirements:
        id:  \d+
    options:
        expose: true
        
event_register:
    path:     /register/{eventid}/{numattendees}
    defaults: { _controller: CptEventBundle:Event:registerForEvent  }
    requirements:
        eventid:  \d+
        numattendees: \d+
    options:
        expose: true   

event_cancel_registration:
    path:     /cancel_registration/{eventid}
    defaults: { _controller: CptEventBundle:Event:cancelRegistration  }
    requirements:
        eventid:  \d+
    options:
        expose: true
        
        
event_was_updated:
    path:     /edit/{id}/wasupdated/{unixtimestamp}
    defaults: { _controller: CptEventBundle:Event:wasEventUpdated }
    requirements:
        id:  \d+
        unixtimestamp: \d+

event_download_attendees:
    path:     /downloadattendees/{eventid}
    defaults: { _controller: CptEventBundle:Event:downloadAttendees  }
    requirements:
        eventid:  \d+
    
cpt_search_user:
    pattern: /usersearch
    defaults: { _controller: CptEventBundle:Event:userSearch }
    
cpt_user_getsearchresult:
    pattern: /usersearch/query
    defaults: { _controller: CptEventBundle:Event:userGetSearchResult }

        
event_view_calendar:
    path:     /calendar/{year}/{month}
    defaults: { _controller: CptEventBundle:Calendar:viewCalendar }
    requirements:
        year:  \d+
        month: \d+
    options:
        expose: true
        
event_get_events_for_month:
    path:     /events/{year}/{month}
    defaults: { _controller: CptEventBundle:Event:getEventsForMonth }
    requirements:
        year:  \d+
        month: \d+
    options:
        expose: true

event_get_events_for_id:
    path:     /eventid/{id}
    defaults: { _controller: CptEventBundle:Event:getEventsForId }
    requirements:
        id:  \d+
    options:
        expose: true

