# app/config/config.yml
parameters:
    cpt.event.event.manager.class:         Cpt\EventBundle\Manager\EventManager
    cpt.event.event.entity:                 Cpt\EventBundle\Entity\Comment
    cpt.event.calendar.manager.class:      Cpt\EventBundle\Manager\CalendarManager

services:
    cpt.event.manager:
        class:        "%cpt.event.event.manager.class%"
        arguments:    ["@service_container",  %cpt.event.event.entity%]
        # This declares the class as an event provider for the calendr library:
        tags: 
            - { name: calendr.event_provider }

    cpt.calendar.manager:
        class:        "%cpt.event.calendar.manager.class%"
        arguments:    ["@service_container",  %cpt.event.event.entity%]
        # This declares the class as an event provider for the calendr library:
        tags: 
            - { name: calendr.event_provider }
            
    cpt_edit_event:
      class: Cpt\EventBundle\Form\Type\EventType
      tags:
         -  { name: form.type }
         
    cpt.twig.make_js_string_extension:
        class: Cpt\EventBundle\Twig\MakeJsStringExtension
        tags:
            - { name: twig.extension }
            
    cpt.twig.eventmanager_extension:
        class: Cpt\EventBundle\Twig\EventManagerExtension
        arguments: ['@cpt.event.manager']
        tags:
            - { name: twig.extension }