Cpt\EventBundle\Entity\Event:
  getters:
      id:
        - NotBlank: ~
        - Type:
                type: integer        
      begin:
        - NotBlank: ~
        - Type:
                type: datetime
      content:
        - NotBlank: { message: "event.content.not_blank" }
        - Type:
                type: string 
      title:
        - NotBlank: { message: "event.title.not_blank" }
        - Type:
                type: string 
        - Length:
                min: 5
                max: 50
                minMessage: "event.title.min_length"
                maxMessage: "event.title.max_length"
      maxnumattendees:
        - NotBlank: ~
        - Type:
                type: integer
        - Range:
                min: 2
                minMessage: "event.maxnumattendees.min_length"
      end:
        - Type:
                type: datetime 
      createdAt:
        - Type:
                type: datetime 
      updatedAt:
        - Type:
                type: datetime 
      countqueuedattendees:
        - Type:
                type: integer
      counttotalattendees:
        - Type:
                type: integer
      restricted:
        - Type:
                type: bool
      approved:
        - Type:
                type: bool
      cptevent:
        - NotBlank: ~
        - Type:
                type: bool       
      countrycode:
        - NotBlank: { message: "event.country_code.not_blank" }
        - Country:
        - Length:
                min: 2
                max: 2
      cityname:
        - NotBlank: { message: "event.cityname.not_blank" }
        - Type:
                type: string
      citypostalcode:
        - Type:
                type: string  
      address:
        - Type:
                type: string
      corporatename:
        - NotBlank: { message: "event.corporate_name.not_blank" }
        - Type:
                type: string
        - Length:
                min: 3
                max: 30
                minMessage: "event.corporatename.min_length"
                maxMessage: "event.corporatename.max_length"

Cpt\EventBundle\Entity\Registration:
      constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: user, event