Cpt\MainBundle\Entity\Pager:
    exclusion_policy: ALL
    properties:
        isfirstpage:
            exclude: false
            expose: true
            type: boolean
            since_version: 1.0
        page:
            exclude: false
            expose: true
            type: string
            since_version: 1.0
        havetopaginate:
            exclude: false
            expose: true
            type: boolean
            since_version: 1.0    
        firstpage:
            exclude: false
            expose: true
            type: integer
            since_version: 1.0               
        lastPage:
            exclude: false
            expose: true
            type: integer
            since_version: 1.0              
        maxpagelinks:
            exclude: false
            expose: true
            type: integer
            since_version: 1.0              
        nextpage:
            exclude: false
            expose: true
            type: integer
            since_version: 1.0      
        previouspage:
            exclude: false
            expose: true
            type: integer
            since_version: 1.0
        islastpage:
            exclude: false
            expose: true
            type: boolean
            since_version: 1.0 
