<?php

namespace Cpt\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{
}
