parameters:
    cpt.publication.comment.nbretreive: 3 # Number of comments to be retreived each time
    cpt.publication.comment.initialnbretreive: 5 # Initial Number of comments to be retreived each time
    cpt.publication.comment.checkfornew_interval: 120000 # interval in ms to check for new comments
    cpt.blog.max_article_perpage: 8 # max number of articles per page
    cpt.blog.max_page_link: 8 # Number of link in the navigation pager
    cpt.event.update_ajax_delay: 400 # Delay in ms between changes in month and sending request ajax to update calendar, events etc.
    cpt.notice.slideupdelay: 20000  #delay when display a flash message, before the message is hidden
    cpt.ckeditor.ready.timeout: 1500 #delay to get the CKEDITOR ready before accessing it
    cpt.newsletter.send: true;
    cpt.newsletter.interval: "P7D"
    
twig:
  globals:
    cpt_comment_checkfornew_interval: %cpt.publication.comment.checkfornew_interval% # interval in ms to check for new comments
    cpt_notice_slideupdelay: %cpt.notice.slideupdelay%
    CKEDITOR_READY_TIMEOUT: %cpt.ckeditor.ready.timeout%