ivory_ck_editor:
    plugins:
      oembed:
          path: "bundles/applicationivoryckeditor/plugins/oembed/"
          filename: "plugin.js"
      pastetext:
          path: "bundles/applicationivoryckeditor/plugins/pastetext/"
          filename: "plugin.js"
    configs:
        article_config:
            toolbar:                [ [ "DocProps", "-", "Preview", "-", "Print", "Maximize" ], "/", [ "Bold", "Italic", "Underline", "Subscript", "Superscript", "-", "RemoveFormat", "-", "oembed"] ]
            ui_color:               "#ffffff"
            extraPlugins:           "oembed"
            language:               "fr"
            height:                 "200px"
            width:                  "100%"
            font_names:             "'Noto Sans', sans-serif; Geneva; 'Gill Sans'; Tahoma; 'GentiumBasicRegular'"
            forcePasteAsPlainText:  true
        evt_config:
            toolbar:                [ [ "Bold", "Italic", "Underline", "Subscript", "Superscript", "-", "RemoveFormat", "-", "oembed"] ]
            ui_color:               "#ffffff"
            extraPlugins:           "oembed"
            language:               "fr"
            height:                 "80px"
            width:                  "100%"
            font_names:             "'Noto Sans', sans-serif; Geneva; 'Gill Sans'; Tahoma; 'GentiumBasicRegular'"
            forcePasteAsPlainText:  true