cpt_home:
    prefix:     /{_locale}
    resource: "@CptMainBundle/Resources/config/routing.yml"
    requirements:
        _locale: en|fr

cpt_publication:
    resource: "@CptPublicationBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/publication
    requirements:
        _locale: en|fr

cpt_event:
    resource: "@CptEventBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/events
    requirements:
        _locale: en|fr

news:
    resource: '@CptBlogBundle/Resources/config/routing/news.xml'
    prefix:   /{_locale}/articles
    requirements:
        _locale: en|fr
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /sonataprofile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"