services:
    custom_user_manager:
      class: Cpt\MainBundle\Manager\UserManager
      parent: fos_user.user_manager.default
      
#friend of symfony/user bundle configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    service:
        user_manager: custom_user_manager
        # using custom cpt mail manager
        mailer: cpt.mailer.manager 
    registration:
        form:
            type: application_user_registration
        confirmation:
            enabled: true
            from_email:
                address:        donotreply@chantpourtous.com
                sender_name:    Chant Pour Tous
    resetting:
            email:
                from_email:
                    address:        donotreply@chantpourtous.com
                    sender_name:    Chant Pour Tous
                    
sonata_user:
    security_acl:           false
    impersonating_route:    cpt_main_home # or any route you want to use
    class:
        user:               Application\Sonata\UserBundle\Entity\User
        group:              Application\Sonata\UserBundle\Entity\Group
    profile:
        register:
            # This allows you to specify where you want your user redirected once he activated his account
            confirm:
                redirect:
                    # Set it to false to disable redirection
                    route: 'cpt_main_home'
                    route_parameters: ~
