<?php

namespace Cpt\CommentBundle\Entity
;
use Cpt\CommentBundle\Entity\TestBaseComment as TestBaseComment;


/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class TestArticleComment extends TestBaseComment
{
}

?>
