Cpt\EventBundle\Entity\Event:
    type: entity
    repositoryClass: Cpt\EventBundle\Entity\EventRepository
    lifecycleCallbacks:
        prePersist: [prePersist]
        preUpdate: [preUpdate]
    oneToMany:
      registrations:
        targetEntity: Registration
        mappedBy: event
        cascade: ["persist"]
    fields:
      begin:
        type: datetime
      end:  
        type: datetime
      maxnumattendees:
        type: integer
      count_queued_attendees:
        type: integer
      count_total_attendees:
        type: integer
      queue:
        type: simple_array
      registration_allowed:
        type: boolean
      restricted:
        type: boolean
      approved:
        type: boolean
      cpt_event:
        type: boolean        
      country_code:
        type: text
      city_name:
        type: text
      city_postal_code:
        type: text
        nullable: true
      street:
        type: text
        nullable: true
      street_number:
        type: text
        nullable: true
      additional_address:
        type: text
        nullable: true
      corporate_name:
        type: text
      location_show_map:
        type: boolean
        nullable: false
      location_long:
        type: text
        nullable: true
      location_lat:
        type: text
        nullable: true

