<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cpt\BlogBundle\Entity;

use Cpt\BlogBundle\Entity\BaseComment as BaseComment;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Comment extends BaseComment
{
    public function toViewArray()
    {
    return Array(
        "id" => $this->getId(),
        "authorname" => $this->getAuthor()->getDisplayName(),
        "canmodify" => $this->getCanModify(),
        "message" => $this->getMessage(),
        "createdat" => $this->getCreatedAt()->format('d/m/Y'),
        "updatedat" => $this->getUpdatedAt(),
        "postid" =>  $this->getPost()->getId(),
        );
    }
    
    /**
     * @var integer $id
     */
    protected $id;

    protected $author;
    
    protected $canModify = false; // non-mapped field
    
        /**
     * {@inheritdoc}
     */
    public function setAuthor($author)
    {
        $this->author = $author;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthor()
    {
        return $this->author;
    }
    
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function areCommentAndPostAuthorSame()
    {
        $commentAuthor = $this->getAuthor();
        $postAuthor = $this->getPost()->getAuthor();
        
        if ((!$commentAuthor)||(!$postAuthor))
            return false;
        
        return ($commentAuthor->getId() == $postAuthor->getId());
    }
    
    public function setCanModify($value)
    {
        $this->canModify = $value;
    }
    
    public function getCanModify()
    {
        return $this->canModify;
    }
    
    }