<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Cpt\BlogBundle\Entity;

use Cpt\BlogBundle\Entity\BasePost as BasePost;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Post extends BasePost
{
    
    public function toViewArray()
    {
    return Array(
        "id" => $this->getId(),
        "PublishedHomePage" => $this->getPublishedHomePage(),
        "CommentsCount" => $this->getCommentsCount(),
        "AuthorName" => $this->getAuthor()->getDisplayName(),
        "title" => $this->getTitle(),
        "rawContent" => $this->getRawContent()
        );
    }
    
    /**
     * @var integer $id
     */
    protected $id;
    
    protected $canBeCommented; // Unmapped field
    
    protected $canbemodified; // unmapped field

    protected $publishedhomepage;
 
    public function __construct()
    {
        parent::__construct();

        $this->publishedhomepage = false;
        $this->canBeCommented = true;
    }
    
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function setId($id)
    {
        $this->id = $id;
    }
    
    public function getPublishedHomePage()
    {
        return $this->publishedhomepage;
    }

    public function setPublishedHomePage($value)
    {
        $this->publishedhomepage = $value;
    }
    
    public function getCanBeCommented()
    {
        return $this->canBeCommented;
    }
    
    public function setCanBeCommented($value)
    {
        $this->canBeCommented = $value;
    }
    
    public function getCanBeModified()
    {
        return $this->canbemodified;
    }
    
    public function setCanBeModified($value)
    {
        $this->canbemodified = $value;
    }
    
    
}