services:
    cpt.useroption.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments:
            - cpt_useroption                         # name of the form
            - cpt_useroption_form_type               # alias of the form type
            - null                                   # data to bind, this is where your entity could go if you have that defined as a service
            - { attr: {id: useroptionform} , validation_groups: [Default] }       # validation groups
            
            
    cpt.useroption.form.type:
      class: Cpt\MainBundle\Form\Type\UserOptionFormType
      arguments: [%cpt.entity.useroption.class%]
      tags:
         -  { name: form.type, alias: cpt_useroption_form_type }    #alias of for tag as referenced by cpt.useroption.form
         
    cpt.useroption.form.handler:
      class: Cpt\MainBundle\Form\Handler\UserOptionFormHandler
      arguments: 
            - @cpt.useroption.form
            - @request_stack
            - @fos_user.user_manager
            - @cpt.mailer.manager

    cpt_form_user:
      class: Cpt\MainBundle\Form\Type\UserType
      tags:
         -  { name: form.type }
         
    cpt.registration.form.type:
        class: Application\FOS\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_registration }