cpt_base_article_permalink:
    pattern:  /permalink/article/{article_permalink}
    defaults: { _controller: CptMainBundle:Default:showArticle }
    requirements:
        article_permalink:  .+?

cpt_base_event_permalink:
    pattern:  /permalink/event/{event_permalink}
    defaults: { _controller: CptMainBundle:Default:showEvent }
    requirements:
        event_permalink:  .+?
        
cpt_main_home:
    pattern:  /home
    defaults: { _controller: CptMainBundle:Default:index }
        
cpt_main_useradmin:
  pattern:  /useradmin
  defaults: { _controller: CptMainBundle:UserAdmin:index }
  
cpt_main_userprofile_show:
    pattern:  /profile/{userid}
    defaults: { _controller: CptMainBundle:User:showProfile }
    requirements:
        userid:  \d+
    options:
        expose: true

cpt_main_userprofile_edit:
    pattern:  /profile/edit
    defaults: { _controller: CptMainBundle:User:editProfile }

cpt_main_userparameters:
    pattern:  /profile/parameters
    defaults: { _controller: CptMainBundle:User:editParameters }


cpt_main_sendprivateemail:
    pattern:  /profile/{userid}/sendemail
    defaults: { _controller: CptMainBundle:User:sendPrivateEmail}
    requirements:
        userid:  \d+
    
     
cpt_main_about:
    pattern:  /about
    defaults: { _controller: CptMainBundle:Default:about }
    options:
        expose: true

    
cpt_send_newsletter:
    pattern:  /sendnewsletter
    defaults: { _controller: CptMainBundle:Default:sendNewsLetter } 
    
cpt_post_facebook:
    pattern:  /postfacebook
    defaults: { _controller: CptMainBundle:Default:postFacebook }
    
cpt_search_user:
    pattern: /usersearch
    defaults: { _controller: CptMainBundle:User:userSearch }
    
cpt_user_getsearchresult:
    pattern: /usersearch/query
    defaults: { _controller: CptMainBundle:User:userGetSearchResult }