# app/config/config.yml
parameters:
    cpt.manager.permissionManager.class:      Cpt\MainBundle\Manager\PermissionsManager
    cpt.manager.mailerManager.class:           Cpt\MainBundle\Manager\MailManager
    cpt.mailer.template.resetting:              CptMainBundle:Emails:resetting_email.txt.twig
    cpt.mailer.template.registration:              CptMainBundle:Emails:registration_email.txt.twig
    cpt.mail.from_email:                        donotreply@chantpourtous.com

services:
    cpt.permission.manager:
        class:        "%cpt.manager.permissionManager.class%"
        arguments: ['@service_container']
        
    cpt_form_user:
      class: Cpt\MainBundle\Form\Type\UserType
      tags:
         -  { name: form.type }
         
    cpt.registration.form.type:
        class: Application\FOS\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: application_user_registration }         

    cpt.mailer.manager:
        class:   "%cpt.manager.mailerManager.class%"
        arguments: 
            - '@service_container'
            - '@mailer'
            - '@router'
            - '@templating'
            - { confirmation.template: %cpt.mailer.template.registration%, resetting.template: %cpt.mailer.template.resetting%, from_email: {confirmation: %cpt.mail.from_email%, resetting: %cpt.mail.from_email%} }