# app/config/config.yml
parameters:
    cpt.manager.permissionManager.class:      Cpt\MainBundle\Manager\PermissionsManager

services:
    cpt.permission.manager:
        class:        "%cpt.manager.permissionManager.class%"
        arguments: ['@service_container']